name: 'Update NPM Deps'
description: 'GitHub Action to update NPM dependencies in protected branches'
inputs:
  commit:  # id of input
    description: 'Commit changes to package.json and package-lock.json'
    required: false
    default: 'false'
outputs:
  publish: # id of output
    description: 'Branch is in release config and eligible for publish'
runs:
  using: 'node12'
  main: 'index.js'
